# Generated by Django 5.1.1 on 2024-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(max_length=5)),
                ('order_id', models.IntegerField(max_length=5, unique=True)),
                ('order_status', models.CharField(verbose_name='')),
            ],
        ),
    ]
